spring:
  application:
    name: website_sample
  main:
    banner-mode: "off"
  thymeleaf:
    cache: false
    prefix: classpath:/static/public/

server:
  error:
    whitelabel:
      enabled: true
    include-stacktrace: always
  address: localhost
  port: ${PORT:8080}
logging:
  ##pattern:
    ##console: "%d{HH:mm:ss.SSS} %logger{40}.%M\\(%class{0}.java:%line\\) - %msg%throwable%n"
  level:
    root: WARN
  org:
    springframework:
      boot:
        test:
          context:
            SpringBootTestContextBootstrapper: WARN
      test:
        context:
          support:
            AbstractContextLoader: OFF
            AnnotationConfigContextLoaderUtils: OFF
  com:
    devhow:
      identity:
        user:
          EmailSenderService: INFO
external:
  server:
    address: http://localhost:8080 # Do not include trailing slash